### ISSUE TITLE
项目不能正常跑起来

### ISSUE THREAD

**Issue by ZakAnun** [haodongLing/MusicPlayer#1]
1、butterknife 版本较低，升级后正常运行
2、id 使用错误，导致运行崩溃，修改后可以正常运行

问题，正常运行后不能播放音频，发现 service 没有注册在 maninfest 里面，但添加后，依然不能播放那个 url，请问这个 demo 还有维护吗？

**Comment by haodongLing** [comment]
has fixed

**Comment by haodongLing** [comment]
当时没有仔细看，抱歉~
